/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contractFb4E48Dd3ASol from "./contract-fb4e48dd3a.sol";
export type { contractFb4E48Dd3ASol };
export type { KitnDisbursement } from "./KitnDisbursement";
