/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as contractFb4E48Dd3ASol from "./contract-fb4e48dd3a.sol";
export { KitnDisbursement__factory } from "./KitnDisbursement__factory";
