/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { KitnDisbursement__factory } from "./KitnDisbursement__factory";
export { Wallet__factory } from "./Wallet__factory";
