/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface KitnDisbursementInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "KITN_ADDRESS"
      | "getWalletBalance"
      | "kitnToken"
      | "myAllowance"
      | "owner"
      | "renewAllowance"
      | "spendCoins"
      | "users"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AllowanceRenewed" | "CoinsSpent"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "KITN_ADDRESS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWalletBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "kitnToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "myAllowance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renewAllowance",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "spendCoins",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "users", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "KITN_ADDRESS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWalletBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kitnToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "myAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renewAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "spendCoins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "users", data: BytesLike): Result;
}

export namespace AllowanceRenewedEvent {
  export type InputTuple = [
    user: AddressLike,
    allowance: BigNumberish,
    timeLimit: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    allowance: bigint,
    timeLimit: bigint
  ];
  export interface OutputObject {
    user: string;
    allowance: bigint;
    timeLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoinsSpentEvent {
  export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [receiver: string, amount: bigint];
  export interface OutputObject {
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface KitnDisbursement extends BaseContract {
  connect(runner?: ContractRunner | null): KitnDisbursement;
  waitForDeployment(): Promise<this>;

  interface: KitnDisbursementInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  KITN_ADDRESS: TypedContractMethod<[], [string], "view">;

  getWalletBalance: TypedContractMethod<[], [bigint], "view">;

  kitnToken: TypedContractMethod<[], [string], "view">;

  myAllowance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renewAllowance: TypedContractMethod<
    [_user: AddressLike, _allowance: BigNumberish, _timeLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  spendCoins: TypedContractMethod<
    [_receiver: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  users: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        userAddress: string;
        allowance: bigint;
        validity: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "KITN_ADDRESS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getWalletBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "kitnToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "myAllowance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renewAllowance"
  ): TypedContractMethod<
    [_user: AddressLike, _allowance: BigNumberish, _timeLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "spendCoins"
  ): TypedContractMethod<
    [_receiver: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "users"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint] & {
        userAddress: string;
        allowance: bigint;
        validity: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AllowanceRenewed"
  ): TypedContractEvent<
    AllowanceRenewedEvent.InputTuple,
    AllowanceRenewedEvent.OutputTuple,
    AllowanceRenewedEvent.OutputObject
  >;
  getEvent(
    key: "CoinsSpent"
  ): TypedContractEvent<
    CoinsSpentEvent.InputTuple,
    CoinsSpentEvent.OutputTuple,
    CoinsSpentEvent.OutputObject
  >;

  filters: {
    "AllowanceRenewed(address,uint256,uint256)": TypedContractEvent<
      AllowanceRenewedEvent.InputTuple,
      AllowanceRenewedEvent.OutputTuple,
      AllowanceRenewedEvent.OutputObject
    >;
    AllowanceRenewed: TypedContractEvent<
      AllowanceRenewedEvent.InputTuple,
      AllowanceRenewedEvent.OutputTuple,
      AllowanceRenewedEvent.OutputObject
    >;

    "CoinsSpent(address,uint256)": TypedContractEvent<
      CoinsSpentEvent.InputTuple,
      CoinsSpentEvent.OutputTuple,
      CoinsSpentEvent.OutputObject
    >;
    CoinsSpent: TypedContractEvent<
      CoinsSpentEvent.InputTuple,
      CoinsSpentEvent.OutputTuple,
      CoinsSpentEvent.OutputObject
    >;
  };
}
